runtime: python39
# runtime: custom
# api_version: 1
#threadsafe: true
# env: flex
# entrypoint: gunicorn -b :$PORT main:app
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

handlers:
  - url: /.*
    script: main.app